telegram:
  token: # telegram-token
  proxy: # telegram-socks5-proxy
  workers: 10

logger:
  level: debug
  format: console
  trace_level: error
  no_disclaimer: true

workers:
  bot:
    immediately: true
